apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk2
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium-v2
  resources:
    requests:
      storage: 1Gi
